const planetasInfo = {
    Sol: {
        nome: "Sol",
        imagem: "./img/planetsIcons/sol.png",
        massa: "1.989 x 10^30 kg",
        raio: "696.340 km",
        temperaturaMedia: "5.500°C",
        tempoDeTranslacao: "Não aplicável (é a estrela central do sistema solar)",
        distanciaDoSol: "0 km",
        descricao: "O Sol é a estrela no centro do nosso sistema solar. Ele é a fonte primária de luz e calor para os planetas ao seu redor.",
    },
    Mercúrio: {
        nome: "Mercúrio",
        imagem: "./img/planetsIcons/mercurio.jpg",
        massa: "3.3011 x 10^23 kg",
        raio: "2.439 km",
        temperaturaMedia: "167°C",
        tempoDeTranslacao: "88 dias terrestres",
        distanciaDoSol: "57,91 milhões de km",
        descricao: "Mercúrio é o planeta mais próximo do Sol. É um planeta rochoso e não tem atmosfera significativa.",
    },
    Vênus: {
        nome: "Vênus",
        imagem: "./img/planetsIcons/venus.png",
        massa: "4.867 x 10^24 kg",
        raio: "6.051,8 km",
        temperaturaMedia: "464°C",
        tempoDeTranslacao: "225 dias terrestres",
        distanciaDoSol: "108,2 milhões de km",
        descricao: "Vênus é o planeta mais parecido com a Terra em termos de tamanho, mas sua atmosfera densa e quente torna-o inóspito.",
    },
    Terra: {
        nome: "Terra",
        imagem: "./img/planetsIcons/terra.jpg",
        massa: "5.972 x 10^24 kg",
        raio: "6.371 km",
        temperaturaMedia: "15°C",
        tempoDeTranslacao: "365,25 dias terrestres",
        distanciaDoSol: "149,6 milhões de km",
        descricao: "A Terra é o único planeta conhecido por abrigar vida. Possui uma atmosfera rica em oxigênio e água em estado líquido.",
    },
    Marte: {
        nome: "Marte",
        imagem: "./img/planetsIcons/marte.png",
        massa: "6.4171 x 10^23 kg",
        raio: "3.396,2 km",
        temperaturaMedia: "-63°C",
        tempoDeTranslacao: "687 dias terrestres",
        distanciaDoSol: "227,9 milhões de km",
        descricao: "Marte, o 'planeta vermelho', é o quarto planeta a partir do Sol. Possui características semelhantes à Terra, incluindo calotas polares e um clima frio.",
    },
    Júpiter: {
        nome: "Júpiter",
        imagem: "./img/planetsIcons/jupiter.jpg",
        massa: "1.898 × 10^27 kg",
        raio: "69.911 km",
        temperaturaMedia: "-108°C",
        tempoDeTranslacao: "11,86 anos terrestres",
        distanciaDoSol: "778,3 milhões de km",
        descricao: "Júpiter é o maior planeta do sistema solar. É um gigante gasoso, com uma atmosfera composta principalmente de hidrogênio e hélio.",
    },
    Saturno: {
        nome: "Saturno",
        imagem: "./img/planetsIcons/saturno.jpg",
        massa: "5.683 x 10^26 kg",
        raio: "58.232 km",
        temperaturaMedia: "-139°C",
        tempoDeTranslacao: "29,46 anos terrestres",
        distanciaDoSol: "1.429 milhões de km",
        descricao: "Saturno é famoso pelos seus anéis. É um gigante gasoso composto principalmente de hidrogênio e hélio.",
    },
    Urano: {
        nome: "Urano",
        imagem: "./img/planetsIcons/urano.png",
        massa: "8.681 × 10^25 kg",
        raio: "25.362 km",
        temperaturaMedia: "-224°C",
        tempoDeTranslacao: "84 anos terrestres",
        distanciaDoSol: "2.870 milhões de km",
        descricao: "Urano é um gigante gasoso que possui uma inclinação extrema em seu eixo de rotação, causando uma rotação quase lateral. Sua cor característica vem do metano em sua atmosfera.",
    },
    Netuno: {
        nome: "Netuno",
        imagem: "./img/planetsIcons/netuno.png",
        massa: "1.024 x 10^26 kg",
        raio: "24.622 km",
        temperaturaMedia: "-218°C",
        tempoDeTranslacao: "164,8 anos terrestres",
        distanciaDoSol: "4.498 milhões de km",
        descricao: "Netuno é o oitavo planeta a partir do Sol e é conhecido por seus ventos extremamente fortes. Sua atmosfera é composta principalmente de hidrogênio, hélio e metano.",
    },
    Plutão: {
        nome: "Plutão",
        imagem: "./img/planetsIcons/plutao.png",
        massa: "1.303 x 10^22 kg",
        raio: "1.188,3 km",
        temperaturaMedia: "-229°C",
        tempoDeTranslacao: "248 anos terrestres",
        distanciaDoSol: "5.906 milhões de km",
        descricao: "Plutão foi reclassificado como planeta anão. É composto principalmente de rochas e gelo e tem uma órbita altamente excêntrica.",
    },
};

export default planetasInfo;